// <auto-generated />
namespace AutomatedTellerMachine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview2-19525-03")]
    public sealed partial class pin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pin));
        
        string IMigrationMetadata.Id
        {
            get { return "201911030041112_pin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
